// Code generated by protoc-gen-go.
// source: GameObject.proto
// DO NOT EDIT!

package spacecluster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GameObjState struct {
	XPos             *uint32  `protobuf:"varint,1,req,name=XPos,json=xPos" json:"XPos,omitempty"`
	YPos             *uint32  `protobuf:"varint,2,req,name=YPos,json=yPos" json:"YPos,omitempty"`
	Size             *uint32  `protobuf:"varint,3,req,name=Size,json=size" json:"Size,omitempty"`
	Velocity         *float32 `protobuf:"fixed32,4,req,name=Velocity,json=velocity" json:"Velocity,omitempty"`
	Azimuth          *float32 `protobuf:"fixed32,5,req,name=Azimuth,json=azimuth" json:"Azimuth,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GameObjState) Reset()                    { *m = GameObjState{} }
func (m *GameObjState) String() string            { return proto.CompactTextString(m) }
func (*GameObjState) ProtoMessage()               {}
func (*GameObjState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GameObjState) GetXPos() uint32 {
	if m != nil && m.XPos != nil {
		return *m.XPos
	}
	return 0
}

func (m *GameObjState) GetYPos() uint32 {
	if m != nil && m.YPos != nil {
		return *m.YPos
	}
	return 0
}

func (m *GameObjState) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *GameObjState) GetVelocity() float32 {
	if m != nil && m.Velocity != nil {
		return *m.Velocity
	}
	return 0
}

func (m *GameObjState) GetAzimuth() float32 {
	if m != nil && m.Azimuth != nil {
		return *m.Azimuth
	}
	return 0
}

type GameObjUpdate struct {
	ObjId            *string       `protobuf:"bytes,2,req,name=ObjId,json=objId" json:"ObjId,omitempty"`
	ObjState         *GameObjState `protobuf:"bytes,3,req,name=ObjState,json=objState" json:"ObjState,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GameObjUpdate) Reset()                    { *m = GameObjUpdate{} }
func (m *GameObjUpdate) String() string            { return proto.CompactTextString(m) }
func (*GameObjUpdate) ProtoMessage()               {}
func (*GameObjUpdate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GameObjUpdate) GetObjId() string {
	if m != nil && m.ObjId != nil {
		return *m.ObjId
	}
	return ""
}

func (m *GameObjUpdate) GetObjState() *GameObjState {
	if m != nil {
		return m.ObjState
	}
	return nil
}

func init() {
	proto.RegisterType((*GameObjState)(nil), "spacecluster.GameObjState")
	proto.RegisterType((*GameObjUpdate)(nil), "spacecluster.GameObjUpdate")
}

var fileDescriptor2 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x70, 0x4f, 0xcc, 0x4d,
	0xf5, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0x2e,
	0x48, 0x4c, 0x4e, 0x4d, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0x52, 0x6a, 0x60, 0xe4, 0xe2, 0x81,
	0x2a, 0x09, 0x2e, 0x49, 0x2c, 0x49, 0x15, 0x12, 0xe2, 0x62, 0x89, 0x08, 0xc8, 0x2f, 0x96, 0x60,
	0x54, 0x60, 0xd2, 0xe0, 0x0d, 0x62, 0xa9, 0x00, 0xb2, 0x41, 0x62, 0x91, 0x20, 0x31, 0x26, 0x88,
	0x58, 0x25, 0x54, 0x2c, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x19, 0x22, 0x56, 0x0c, 0x64, 0x0b, 0x49,
	0x71, 0x71, 0x84, 0xa5, 0xe6, 0xe4, 0x27, 0x67, 0x96, 0x54, 0x4a, 0xb0, 0x00, 0xc5, 0x99, 0x82,
	0x38, 0xca, 0xa0, 0x7c, 0x21, 0x09, 0x2e, 0x76, 0xc7, 0xaa, 0xcc, 0xdc, 0xd2, 0x92, 0x0c, 0x09,
	0x56, 0xb0, 0x14, 0x7b, 0x22, 0x84, 0xab, 0x14, 0xcb, 0xc5, 0x0b, 0x75, 0x41, 0x68, 0x41, 0x0a,
	0xc8, 0x09, 0x22, 0x5c, 0xac, 0x40, 0x8e, 0x67, 0x0a, 0xd8, 0x3e, 0xce, 0x20, 0xd6, 0x7c, 0x10,
	0x47, 0xc8, 0x8c, 0x8b, 0x03, 0xe6, 0x48, 0xb0, 0xa5, 0xdc, 0x46, 0x52, 0x7a, 0xc8, 0x5e, 0xd1,
	0x43, 0xf6, 0x46, 0x10, 0x47, 0x3e, 0x94, 0x05, 0x08, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x3f, 0x07,
	0x4a, 0x02, 0x01, 0x00, 0x00,
}
