// Code generated by protoc-gen-go.
// source: GameEvent.proto
// DO NOT EDIT!

/*
Package spacecluster is a generated protocol buffer package.

It is generated from these files:
	GameEvent.proto
	GameHeartbeat.proto
	GameObject.proto
	Message.proto
	ServerInfo.proto

It has these top-level messages:
	GameEvent
	PlayerJoinedPayload
	PlayerLeftPayload
	ObjectAbsorbedPayload
	ObjectDestroyedPayload
	ObjectSplitPayload
	CreateObjectPayload
	GameHeartbeat
	GameObjState
	GameObjUpdate
	Message
	ServerInfo
*/
package spacecluster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Server-initiated message
type GameEvent struct {
	InitObjId   *string `protobuf:"bytes,3,req,name=InitObjId,json=initObjId" json:"InitObjId,omitempty"`
	TargetObjId *string `protobuf:"bytes,4,req,name=TargetObjId,json=targetObjId" json:"TargetObjId,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*GameEvent_PlayerJoined
	//	*GameEvent_PlayerLeft
	//	*GameEvent_ObjectAbsorbed
	//	*GameEvent_ObjectDestroyed
	//	*GameEvent_ObjectSplit
	//	*GameEvent_CreateObject
	Payload          isGameEvent_Payload `protobuf_oneof:"Payload"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GameEvent) Reset()                    { *m = GameEvent{} }
func (m *GameEvent) String() string            { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()               {}
func (*GameEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isGameEvent_Payload interface {
	isGameEvent_Payload()
}

type GameEvent_PlayerJoined struct {
	PlayerJoined *PlayerJoinedPayload `protobuf:"bytes,5,opt,name=PlayerJoined,json=playerJoined,oneof"`
}
type GameEvent_PlayerLeft struct {
	PlayerLeft *PlayerLeftPayload `protobuf:"bytes,6,opt,name=PlayerLeft,json=playerLeft,oneof"`
}
type GameEvent_ObjectAbsorbed struct {
	ObjectAbsorbed *ObjectAbsorbedPayload `protobuf:"bytes,7,opt,name=ObjectAbsorbed,json=objectAbsorbed,oneof"`
}
type GameEvent_ObjectDestroyed struct {
	ObjectDestroyed *ObjectDestroyedPayload `protobuf:"bytes,8,opt,name=ObjectDestroyed,json=objectDestroyed,oneof"`
}
type GameEvent_ObjectSplit struct {
	ObjectSplit *ObjectSplitPayload `protobuf:"bytes,9,opt,name=ObjectSplit,json=objectSplit,oneof"`
}
type GameEvent_CreateObject struct {
	CreateObject *CreateObjectPayload `protobuf:"bytes,10,opt,name=CreateObject,json=createObject,oneof"`
}

func (*GameEvent_PlayerJoined) isGameEvent_Payload()    {}
func (*GameEvent_PlayerLeft) isGameEvent_Payload()      {}
func (*GameEvent_ObjectAbsorbed) isGameEvent_Payload()  {}
func (*GameEvent_ObjectDestroyed) isGameEvent_Payload() {}
func (*GameEvent_ObjectSplit) isGameEvent_Payload()     {}
func (*GameEvent_CreateObject) isGameEvent_Payload()    {}

func (m *GameEvent) GetPayload() isGameEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GameEvent) GetInitObjId() string {
	if m != nil && m.InitObjId != nil {
		return *m.InitObjId
	}
	return ""
}

func (m *GameEvent) GetTargetObjId() string {
	if m != nil && m.TargetObjId != nil {
		return *m.TargetObjId
	}
	return ""
}

func (m *GameEvent) GetPlayerJoined() *PlayerJoinedPayload {
	if x, ok := m.GetPayload().(*GameEvent_PlayerJoined); ok {
		return x.PlayerJoined
	}
	return nil
}

func (m *GameEvent) GetPlayerLeft() *PlayerLeftPayload {
	if x, ok := m.GetPayload().(*GameEvent_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (m *GameEvent) GetObjectAbsorbed() *ObjectAbsorbedPayload {
	if x, ok := m.GetPayload().(*GameEvent_ObjectAbsorbed); ok {
		return x.ObjectAbsorbed
	}
	return nil
}

func (m *GameEvent) GetObjectDestroyed() *ObjectDestroyedPayload {
	if x, ok := m.GetPayload().(*GameEvent_ObjectDestroyed); ok {
		return x.ObjectDestroyed
	}
	return nil
}

func (m *GameEvent) GetObjectSplit() *ObjectSplitPayload {
	if x, ok := m.GetPayload().(*GameEvent_ObjectSplit); ok {
		return x.ObjectSplit
	}
	return nil
}

func (m *GameEvent) GetCreateObject() *CreateObjectPayload {
	if x, ok := m.GetPayload().(*GameEvent_CreateObject); ok {
		return x.CreateObject
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameEvent_OneofMarshaler, _GameEvent_OneofUnmarshaler, _GameEvent_OneofSizer, []interface{}{
		(*GameEvent_PlayerJoined)(nil),
		(*GameEvent_PlayerLeft)(nil),
		(*GameEvent_ObjectAbsorbed)(nil),
		(*GameEvent_ObjectDestroyed)(nil),
		(*GameEvent_ObjectSplit)(nil),
		(*GameEvent_CreateObject)(nil),
	}
}

func _GameEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameEvent)
	// Payload
	switch x := m.Payload.(type) {
	case *GameEvent_PlayerJoined:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerJoined); err != nil {
			return err
		}
	case *GameEvent_PlayerLeft:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerLeft); err != nil {
			return err
		}
	case *GameEvent_ObjectAbsorbed:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ObjectAbsorbed); err != nil {
			return err
		}
	case *GameEvent_ObjectDestroyed:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ObjectDestroyed); err != nil {
			return err
		}
	case *GameEvent_ObjectSplit:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ObjectSplit); err != nil {
			return err
		}
	case *GameEvent_CreateObject:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateObject); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameEvent.Payload has unexpected type %T", x)
	}
	return nil
}

func _GameEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameEvent)
	switch tag {
	case 5: // Payload.PlayerJoined
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerJoinedPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_PlayerJoined{msg}
		return true, err
	case 6: // Payload.PlayerLeft
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerLeftPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_PlayerLeft{msg}
		return true, err
	case 7: // Payload.ObjectAbsorbed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ObjectAbsorbedPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_ObjectAbsorbed{msg}
		return true, err
	case 8: // Payload.ObjectDestroyed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ObjectDestroyedPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_ObjectDestroyed{msg}
		return true, err
	case 9: // Payload.ObjectSplit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ObjectSplitPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_ObjectSplit{msg}
		return true, err
	case 10: // Payload.CreateObject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateObjectPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &GameEvent_CreateObject{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameEvent)
	// Payload
	switch x := m.Payload.(type) {
	case *GameEvent_PlayerJoined:
		s := proto.Size(x.PlayerJoined)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameEvent_PlayerLeft:
		s := proto.Size(x.PlayerLeft)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameEvent_ObjectAbsorbed:
		s := proto.Size(x.ObjectAbsorbed)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameEvent_ObjectDestroyed:
		s := proto.Size(x.ObjectDestroyed)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameEvent_ObjectSplit:
		s := proto.Size(x.ObjectSplit)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameEvent_CreateObject:
		s := proto.Size(x.CreateObject)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PlayerJoinedPayload struct {
	// InitObjId = ???
	// TargetObjId = Joined Player
	Name             *string `protobuf:"bytes,1,req,name=Name,json=name" json:"Name,omitempty"`
	ObjTheme         *string `protobuf:"bytes,2,req,name=ObjTheme,json=objTheme" json:"ObjTheme,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerJoinedPayload) Reset()                    { *m = PlayerJoinedPayload{} }
func (m *PlayerJoinedPayload) String() string            { return proto.CompactTextString(m) }
func (*PlayerJoinedPayload) ProtoMessage()               {}
func (*PlayerJoinedPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlayerJoinedPayload) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlayerJoinedPayload) GetObjTheme() string {
	if m != nil && m.ObjTheme != nil {
		return *m.ObjTheme
	}
	return ""
}

type PlayerLeftPayload struct {
	// InitObjId = ???
	// TargetObjId = Leaving Player
	LeaveAnimation   *string `protobuf:"bytes,1,opt,name=LeaveAnimation,json=leaveAnimation" json:"LeaveAnimation,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerLeftPayload) Reset()                    { *m = PlayerLeftPayload{} }
func (m *PlayerLeftPayload) String() string            { return proto.CompactTextString(m) }
func (*PlayerLeftPayload) ProtoMessage()               {}
func (*PlayerLeftPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerLeftPayload) GetLeaveAnimation() string {
	if m != nil && m.LeaveAnimation != nil {
		return *m.LeaveAnimation
	}
	return ""
}

type ObjectAbsorbedPayload struct {
	// InitObjId = Absorber (or server, equiv. to destroy)
	// TargetObjId = Absorbed
	NewInitSize      *uint32 `protobuf:"varint,1,req,name=NewInitSize,json=newInitSize" json:"NewInitSize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ObjectAbsorbedPayload) Reset()                    { *m = ObjectAbsorbedPayload{} }
func (m *ObjectAbsorbedPayload) String() string            { return proto.CompactTextString(m) }
func (*ObjectAbsorbedPayload) ProtoMessage()               {}
func (*ObjectAbsorbedPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ObjectAbsorbedPayload) GetNewInitSize() uint32 {
	if m != nil && m.NewInitSize != nil {
		return *m.NewInitSize
	}
	return 0
}

type ObjectDestroyedPayload struct {
	// InitObjId = Destroyer (or server)
	// TargetObjId = Destroyed
	DestroyReason    *string `protobuf:"bytes,1,opt,name=DestroyReason,json=destroyReason" json:"DestroyReason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ObjectDestroyedPayload) Reset()                    { *m = ObjectDestroyedPayload{} }
func (m *ObjectDestroyedPayload) String() string            { return proto.CompactTextString(m) }
func (*ObjectDestroyedPayload) ProtoMessage()               {}
func (*ObjectDestroyedPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ObjectDestroyedPayload) GetDestroyReason() string {
	if m != nil && m.DestroyReason != nil {
		return *m.DestroyReason
	}
	return ""
}

type ObjectSplitPayload struct {
	// InitObjId = Splitting Initiator (or server)
	// TargetObjId = Split Object
	CreatedObjects   []*CreateObjectPayload `protobuf:"bytes,1,rep,name=CreatedObjects,json=createdObjects" json:"CreatedObjects,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ObjectSplitPayload) Reset()                    { *m = ObjectSplitPayload{} }
func (m *ObjectSplitPayload) String() string            { return proto.CompactTextString(m) }
func (*ObjectSplitPayload) ProtoMessage()               {}
func (*ObjectSplitPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ObjectSplitPayload) GetCreatedObjects() []*CreateObjectPayload {
	if m != nil {
		return m.CreatedObjects
	}
	return nil
}

type CreateObjectPayload struct {
	// InitObjId = Parent Object (or server)
	// TargetObjId = New Object
	ObjType          *string       `protobuf:"bytes,2,req,name=ObjType,json=objType" json:"ObjType,omitempty"`
	InitialState     *GameObjState `protobuf:"bytes,3,req,name=InitialState,json=initialState" json:"InitialState,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CreateObjectPayload) Reset()                    { *m = CreateObjectPayload{} }
func (m *CreateObjectPayload) String() string            { return proto.CompactTextString(m) }
func (*CreateObjectPayload) ProtoMessage()               {}
func (*CreateObjectPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateObjectPayload) GetObjType() string {
	if m != nil && m.ObjType != nil {
		return *m.ObjType
	}
	return ""
}

func (m *CreateObjectPayload) GetInitialState() *GameObjState {
	if m != nil {
		return m.InitialState
	}
	return nil
}

func init() {
	proto.RegisterType((*GameEvent)(nil), "spacecluster.GameEvent")
	proto.RegisterType((*PlayerJoinedPayload)(nil), "spacecluster.PlayerJoinedPayload")
	proto.RegisterType((*PlayerLeftPayload)(nil), "spacecluster.PlayerLeftPayload")
	proto.RegisterType((*ObjectAbsorbedPayload)(nil), "spacecluster.ObjectAbsorbedPayload")
	proto.RegisterType((*ObjectDestroyedPayload)(nil), "spacecluster.ObjectDestroyedPayload")
	proto.RegisterType((*ObjectSplitPayload)(nil), "spacecluster.ObjectSplitPayload")
	proto.RegisterType((*CreateObjectPayload)(nil), "spacecluster.CreateObjectPayload")
}

var fileDescriptor0 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xe9, 0x56, 0x68, 0xf3, 0x92, 0xa6, 0xf0, 0x26, 0x50, 0x54, 0x21, 0x51, 0xc2, 0x84,
	0x76, 0xea, 0x61, 0x37, 0x84, 0x34, 0xa9, 0xb0, 0x69, 0x14, 0x8d, 0x51, 0xa5, 0xbb, 0x23, 0x37,
	0x79, 0x80, 0x51, 0x16, 0x47, 0x89, 0x19, 0x2a, 0x7f, 0x06, 0x7f, 0x31, 0x8e, 0x93, 0x25, 0x8e,
	0xea, 0xc3, 0x6e, 0xc9, 0xf7, 0x7d, 0xef, 0x67, 0xfb, 0x3d, 0x1b, 0xa6, 0x97, 0xec, 0x96, 0x2e,
	0xee, 0x28, 0x93, 0x8b, 0xbc, 0x10, 0x52, 0xa0, 0x57, 0xe6, 0x2c, 0xa6, 0x38, 0xfd, 0x5d, 0x4a,
	0x2a, 0x66, 0x4f, 0x2b, 0xfb, 0xeb, 0xf6, 0x17, 0xc5, 0x8d, 0x1f, 0xfe, 0x1b, 0x82, 0xd3, 0xd6,
	0xe0, 0x4b, 0x70, 0x56, 0x19, 0x97, 0x2a, 0xb1, 0x4a, 0x82, 0xc3, 0xf9, 0xc1, 0x89, 0x13, 0x39,
	0xfc, 0x5e, 0xc0, 0x39, 0xb8, 0x37, 0xac, 0xf8, 0x41, 0x8d, 0x3f, 0xd4, 0xbe, 0x2b, 0x3b, 0x09,
	0x2f, 0xc1, 0x5b, 0xa7, 0x6c, 0x47, 0xc5, 0x67, 0xc1, 0x33, 0x4a, 0x82, 0xc7, 0xf3, 0xc1, 0x89,
	0x7b, 0xfa, 0x7a, 0x61, 0x6e, 0x62, 0x61, 0x26, 0xd6, 0x6c, 0x97, 0x0a, 0x96, 0x7c, 0x7a, 0x14,
	0x79, 0xb9, 0x21, 0xe3, 0x12, 0xa0, 0x8e, 0x5d, 0xd1, 0x77, 0x19, 0x3c, 0xd1, 0x98, 0x57, 0x36,
	0x4c, 0xe5, 0x77, 0x10, 0xc8, 0x5b, 0x11, 0xbf, 0x80, 0x5f, 0x9f, 0x74, 0xb9, 0x2d, 0x45, 0xb1,
	0x55, 0xbb, 0x19, 0x69, 0xcc, 0x9b, 0x3e, 0xa6, 0x9f, 0xe9, 0x50, 0xbe, 0xe8, 0x19, 0xb8, 0x86,
	0x69, 0x1d, 0x3d, 0xa7, 0x52, 0x16, 0x62, 0xa7, 0x78, 0x63, 0xcd, 0x3b, 0xb6, 0xf1, 0xda, 0x50,
	0x07, 0x9c, 0x8a, 0xbe, 0x83, 0xe7, 0xe0, 0xd6, 0xe1, 0x4d, 0x9e, 0x72, 0x19, 0x38, 0x9a, 0x36,
	0xb7, 0xd1, 0x74, 0xa0, 0x23, 0xb9, 0xa2, 0x53, 0xab, 0x96, 0x7f, 0x2c, 0x88, 0xc9, 0x66, 0xac,
	0x01, 0xd8, 0x5a, 0x6e, 0x26, 0x8c, 0x96, 0xc7, 0x86, 0xfc, 0xc1, 0x81, 0x51, 0x63, 0x85, 0x17,
	0x70, 0x64, 0x19, 0x12, 0x22, 0x0c, 0xaf, 0xd5, 0x55, 0x09, 0x06, 0x7a, 0xf0, 0xc3, 0x4c, 0x7d,
	0xe3, 0x0c, 0xc6, 0xaa, 0xfe, 0xe6, 0x27, 0x29, 0xfd, 0x40, 0xeb, 0x63, 0xd1, 0xfc, 0x87, 0xef,
	0xe1, 0xd9, 0xde, 0x90, 0xf0, 0x2d, 0xf8, 0x57, 0xc4, 0xee, 0x68, 0x99, 0xf1, 0x5b, 0x26, 0xb9,
	0xc8, 0x14, 0x6e, 0xa0, 0xca, 0xfc, 0xb4, 0xa7, 0x86, 0xef, 0xe0, 0xb9, 0x75, 0x34, 0xd5, 0x2d,
	0xbc, 0xa6, 0x3f, 0xd5, 0x35, 0xdd, 0xf0, 0xbf, 0xf5, 0x66, 0x26, 0x91, 0x9b, 0x75, 0x52, 0x78,
	0x06, 0x2f, 0xec, 0x53, 0xc0, 0x63, 0x98, 0x34, 0x5a, 0x44, 0xac, 0x6c, 0xd7, 0x9e, 0x24, 0xa6,
	0x18, 0x7e, 0x03, 0xdc, 0xef, 0x3b, 0xae, 0xc0, 0xaf, 0xdb, 0x98, 0xd4, 0x66, 0xa9, 0x8a, 0x0f,
	0x1f, 0xd4, 0xea, 0xc8, 0x8f, 0x7b, 0x85, 0xa1, 0x80, 0x23, 0x4b, 0x0c, 0x03, 0x18, 0x55, 0xbd,
	0xdc, 0xe5, 0xf7, 0xad, 0x1c, 0x89, 0xfa, 0x17, 0xcf, 0xc0, 0xab, 0x4e, 0xc7, 0x59, 0xba, 0x91,
	0xaa, 0x4c, 0x3f, 0x4d, 0xf7, 0x74, 0xd6, 0x5f, 0xb9, 0x79, 0xdb, 0x3a, 0x11, 0x79, 0xdc, 0xc8,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xde, 0x93, 0xbe, 0xf5, 0x17, 0x04, 0x00, 0x00,
}
